// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:113728386052:web:abafd80ddbb584993d3151',
    messagingSenderId: '113728386052',
    projectId: 'login-91fd9',
    authDomain: 'login-91fd9.firebaseapp.com',
    storageBucket: 'login-91fd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:113728386052:android:b7effb50c769dec13d3151',
    messagingSenderId: '113728386052',
    projectId: 'login-91fd9',
    storageBucket: 'login-91fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:113728386052:ios:0cfb76d7e4543c963d3151',
    messagingSenderId: '113728386052',
    projectId: 'login-91fd9',
    storageBucket: 'login-91fd9.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBecYPvW5z7Ct8xuSQsgINvcSXWF0_M-H0',
    appId: '1:113728386052:ios:0cfb76d7e4543c963d3151',
    messagingSenderId: '113728386052',
    projectId: 'login-91fd9',
    storageBucket: 'login-91fd9.appspot.com',
    iosBundleId: 'com.example.login',
  );

}
